#!/usr/bin/python3

import os, sys, shutil
import subprocess as sp

path = os.path

min = lambda x, y: (x if (x < y) else y)

def colored(msg, color, *others):
    color = min(int(color), 255)
    
    extras = ';'.join([str(int(x)) for x in others])

    out = ('\033[' + extras + '38;5;' + str(color) + 'm')
    out += msg
    out += '\033[0m'

    return out

def warn(message):
    print(colored(message, 196))

def note(message):
    print(colored(message, 195))

def grab( loc ):
    result = ""
    if path.exists(loc):

        f = open(loc, 'r', 1)
        result += f.read()
        f.close()

    else:
        warn("No file or directory found at '{0}'..")

    return result

def main():
    
    warn( "Hello, World" )
    note( "Hello, World" )


if __name__ == '__main__':
    main()
